---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: event-bus
  name: eda.events.aggregate-metrics
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
    cleanup.policy: delete
  partitions: 1
  replicas: 3
