apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: event-display-kafka-source
spec:
  consumerGroup: event-display-knative-group
  bootstrapServers:
    - event-bus-kafka-bootstrap.eda-workshop.svc:9092
  topics:
    - eda.cloud.events
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display-serverless
