apiVersion: v1
kind: Secret
metadata:
  name: eda-infinispan-credentials
type: Opaque 
stringData: 
  identities.yaml: |-     
    credentials:
    - username: developer
      password: developer
    - username: operator
      password: operator
