---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend-serverless
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: backend-serverless
        app.kubernetes.io/part-of: backend-serverless
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/eda-workshop/backend:1.0.0-SNAPSHOT
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
